/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic18f46k20.h>
#include "fuses_config.h"
#include <macros.h>
//#define KHZ 4000
//#define INSTANTIATE_DELAY
//#include <tsmdelay.h>

volatile char flag=0;

void isr() __interrupt 1 { /*  interrupt service routine */
   
  if(INTCONbits.T0IF){
    INTCONbits.T0IF = 0;// Clear the Timer 0 interrupt.
    
    if(flag==0){
      flag=1;
      BIT_SET(PORTB,3);	// Toggle the state of the LSB of the port bits
      BIT_CLEAR(PORTB,2);
    }
    else{
      BIT_CLEAR(PORTB,3);
      BIT_SET(PORTB,2);
      flag=0;
    }
    
  }
}

void main() {
    
  //TRISA = 0x00;	// All Port A latch outputs are enabled.

  T0CONbits.T0CS = 0;	// Clear to enable timer mode.
  T0CONbits.PSA = 0;	// Clear to assign prescaler to Timer 0.
  T0CONbits.T0PS2 = 0;	// Set up prescaler   
  T0CONbits.T0PS1 = 1;
  T0CONbits.T0PS0 = 1;

  INTCON = 0;	// Clear interrupt flag bits.
  INTCONbits.GIE = 1;	// Enable all interrupts.
  INTCONbits.T0IE = 1;	// Set Timer 0 to 0.  

  TMR0 = 0;	// Enable peripheral interrupts.  
  
  BIT_CLEAR(TRISB, 3); 
  BIT_CLEAR(TRISB, 2);
    
  BIT_CLEAR(PORTB, 3); 
  BIT_CLEAR(PORTB, 2);
  while(1);
  
}
