/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f877.h>
#include <delay.h>
#include "macros.h"
/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _RC_OSC & _WDT_ON & _PWRTE_OFF & _BODEN_ON & _LVP_ON & _CPD_OFF & _WRT_ENABLE_ON & _DEBUG_OFF & _CP_OFF;


unsigned int display[10] ={0x01,0xcf,0x12,0x06,0x4c,0x24,0x20,0x0f,0x00,0x0c} ;//Definicion de Numeros en Display 7 Seg
char i=0;



//    Funcion Principal del Programa, Contador de 0 a 9, segun cambios en RA0
void main()
 {
  TRISB=0;            //Configurar Puerto b como Salidas
  TRISA=1;            //Configurar Puerta.0  como entrada y el resto salida

  while(1)
  {
    PORTB=display[i];
    if (RA0==0)
      {
        delay_ms(200);    // Lamado a Funcion delay_ms includa en libreria delay.h, tiempo aprox 200ms,evitar rebotes
        if (RA0==0)        //if Ra0 es 0 durante 200ms, significa que fue probocada por un rebote
        {
          i++;        //Incremento valor de contador
          if (i==10){    i=0;}  // Si valor el igual a 10 reseteo cuenta
          while(RA0==0);        // Salir solo cuando suelte pulsador en RAO
          }
      }
    }
}