/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f877.h>
#include <macros.h>
#include <delay.h>

/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _RC_OSC & _WDT_ON & _PWRTE_OFF & _BODEN_ON & _LVP_ON & _CPD_OFF & _WRT_ENABLE_ON & _DEBUG_OFF & _CP_OFF;

#define KHZ 4000
#define INSTANTIATE_DELAY
#include <tsmdelay.h>
#define LED  0X06

#include "addup.h"



void main() {
    /* << insert code >> */
    unsigned long j = 0;

    BIT_CLEAR(TRISB, 1); 
    BIT_CLEAR(TRISB, 2);
    
    BIT_SET(PORTB, 1);  
    DELAY_BIG_US(500);
    //delay_ms(500);
    addup(1,1);
    while(1){
      BIT_SET(PORTB, 2); 
      DELAY_BIG_US(1000);
      // delay_ms(1000);
      BIT_TOGGLE(PORTB,1);
    }
  
}
