/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include <pic16f877.h>
#include <macros.h>
/* ----------------------------------------------------------------------- */
/* Configuration bits: adapt to your setup and needs */
typedef unsigned int word;
word __at 0x2007 CONFIG = _RC_OSC & _WDT_OFF & _PWRTE_OFF & _BODEN_ON & _LVP_ON & _CPD_OFF & _WRT_ENABLE_ON & _DEBUG_OFF & _CP_OFF;

void isr() interrupt 0 {                                                                                                         
  /* interrupt service routine */
   
  if(T0IF){
    T0IF = 0;// Clear the Timer 0 interrupt.
    BIT_TOGGLE(PORTB,1);	// Toggle the state of the LSB of the port bits
  }
  if(INTF){
    INTF = 0;
    BIT_TOGGLE(PORTB,2);
  }
}

void main() {
    
  //TRISA = 0x00;	// All Port A latch outputs are enabled.

  T0CS = 0;	// Clear to enable timer mode.
  PSA = 0;	// Clear to assign prescaler to Timer 0.
  PS2 = 0;	// Set up prescaler   
  PS1 = 0;
  PS0 = 1;

  INTCON = 0;	// Clear interrupt flag bits.
  GIE = 1;	// Enable all interrupts.
  T0IE = 1;	  // Enable TMR0 OVERFLOW Interrupts
  INTE = 1;	  //Enable RB0 
  
  
  //INTEDG DRIVES WHEN DOES THE INTERRUPT TRIGGERS
  
  INTEDG = 0; 	//SET OPTION_REG.INTEDG TO BE EDGE_DOWN
  //INTEDG = 1; 	//SET OPTION_REG.INTEDG TO BE EDGE_UP
  
  
  TMR0 = 0;	  // Set Timer 0 to 0.
  
  BIT_SET (TRISB,0);
  BIT_CLEAR(TRISB, 1); 
  BIT_CLEAR(TRISB, 2);
    
  BIT_SET(PORTB, 2);  
  while(1);
  
}
